services:
  - docker

addons:
  hosts:
    - nginx
    - haproxy

jobs:
  include:
    - stage: build&test
      script:
        # Build Image
        - RELEASE=$(grep "RELEASE_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}'); docker build -t polinux/gitlab-ce:$RELEASE .
        - docker build -t polinux/gitlab-ce:latest .
        - RELEASE=$(grep "RELEASE_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}'); docker run -d -p 80:80 --name gitlab -e BACKUP_TIME="0 15 * * *" polinux/gitlab-ce:$RELEASE
        - while true; do if docker logs gitlab | grep "Completed 200 OK in"; then break; else sleep 1; fi done
        # Check connection on port 80
        - curl -sSLi --head http://127.0.0.1 | grep "HTTP/1.1 200 OK"

        # Cahce Image on Docker Hub
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag polinux/gitlab-ce:latest polinux/gitlab-ce:stage
        - docker push polinux/gitlab-ce:stage

    - stage: deploy
      if: branch = master
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker pull polinux/gitlab-ce:stage
        - docker tag polinux/gitlab-ce:stage polinux/gitlab-ce:latest
        - export RELEASE=$(grep "HAPROXY_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}'); docker tag polinux/gitlab-ce:stage polinux/gitlab-ce:$RELEASE
        - docker push polinux/gitlab-ce:latest
        - export RELEASE=$(grep "HAPROXY_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}'); docker push polinux/gitlab-ce:$RELEASE
        - docker push polinux/gitlab-ce:latest